/**
 *
 * DO NOT EDIT THIS FILE!
 *
 * This file is merely a loader for the infinitymint.config.js and you should put inside of the hardhat key what ever you would
 * put inside of here.
 */

//them aliases
import 'module-alias/register';
//import our hardhat plugins
import '@nomicfoundation/hardhat-toolbox';
import '@nomiclabs/hardhat-ethers';
import 'hardhat-deploy';
import 'hardhat-change-network'; //allows hre.changeNetwork to occur
import {
    prepareConfig,
    loadInfinityMint,
    setIgnorePipeFactory,
    hasNodeModule,
    overwriteConsoleMethods,
} from './app/helpers';
import { createDefaultFactory } from './app/pipes';

//create default pipe
createDefaultFactory();
//ovewrite console methods
overwriteConsoleMethods();
//Directly output logs until we have a chance to set the log level
setIgnorePipeFactory(true);

//require dotenv if it exists
if (hasNodeModule('dotenv')) {
    console.log('🧱 Loading .env file');
    require('dotenv').config({
        override: false, //will not override already established environment variables
    });
}
//load infinitymint and create default files
loadInfinityMint(false, true);

//return the infinitymint config file
let config = prepareConfig();

console.log('🧱 Loaded hardhat.config.ts');
export default config.hardhat; //export the infinity mint configuration file
